/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.warehouse.ui.supplier;
import com.app.warehouse.ui.MainFrame;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.SwingUtilities;
import javax.swing.JFrame;
import javax.swing.JPanel;
/**
 *
 * @author MUHAMMAD FADHILLAH
 */
public class SupplierPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierPanel
     */
public SupplierPanel() {
    initComponents();   
    initTable();
    initDesign();       
    setupLayout(); 
}

private void initDesign() {
    // Background utama
    this.setBackground(new java.awt.Color(243, 244, 246));
    panelTop.setBackground(Color.WHITE);

    // Judul
    jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 18));
    jLabel1.setForeground(new Color(30, 58, 138));

    // Button styling
    styleButton(btnAdd, new Color(59, 130, 246));    // biru
    styleButton(btnEdit, new Color(234, 179, 8));    // kuning
    styleButton(btnDelete, new Color(239, 68, 68));  // merah

    // Table styling
    jTable1.setRowHeight(28);
    jTable1.setFont(new Font("Segoe UI", Font.PLAIN, 13));
    jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
    jTable1.getTableHeader().setBackground(new Color(30, 58, 138));
    jTable1.getTableHeader().setForeground(Color.WHITE);
}

private void styleButton(JButton button, Color bg) {
    button.setBackground(bg);
    button.setForeground(Color.WHITE);
    button.setFocusPainted(false);
    button.setFont(new Font("Segoe UI", Font.BOLD, 13));
}

private void setupLayout() {
    // panel pembungkus agar di tengah
    JPanel wrapper = new JPanel(new java.awt.GridBagLayout());
    wrapper.setBackground(new Color(243, 244, 246));

    panelTop.setPreferredSize(new java.awt.Dimension(900, 500));

    wrapper.add(panelTop);

    this.setLayout(new java.awt.BorderLayout());
    this.add(wrapper, java.awt.BorderLayout.CENTER);
}


private void initTable() {
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"ID", "Name", "Contact"}
    ) {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        scrollSupplier = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnDelete.setText("Delete");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollSupplier.setViewportView(jTable1);

        jLabel1.setText("Manage Supplier");

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd))
                .addGap(26, 26, 26)
                .addComponent(scrollSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(169, 169, 169))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
    SupplierFormDialog dialog = new SupplierFormDialog(parent, true);
    dialog.setLocationRelativeTo(parent);
    dialog.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
int row = jTable1.getSelectedRow();

    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Pilih data supplier terlebih dahulu!",
            "Warning",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
    SupplierFormDialog dialog = new SupplierFormDialog(parent);
    dialog.setVisible(true);
   // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed
public static void main(String[] args) {
    SwingUtilities.invokeLater(() -> {
        JFrame frame = new JFrame("Supplier Panel Test");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH); // FULL SCREEN
        frame.setContentPane(new SupplierPanel());
        frame.setVisible(true);
    });
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelTop;
    private javax.swing.JScrollPane scrollSupplier;
    // End of variables declaration//GEN-END:variables
}
