/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.warehouse.ui;

import javax.swing.JFrame;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author MUHAMMAD FADHILLAH
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents(); // WAJIB PALING ATAS

        setTitle("Warehouse Inventory System");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);

        // GANTI NAMA TAB (AMAN)
        tabMain.setTitleAt(0, "📦 Master Data");
        tabMain.setTitleAt(1, "💸 Transaksi");
        tabMain.setTitleAt(2, "📊 Laporan");

        initHeader();
        initPanelDesign();
    }

    private void initHeader() {
        JPanel header = new JPanel(new BorderLayout());
        header.setPreferredSize(new Dimension(0, 60));
        header.setBackground(new Color(30, 58, 138)); // biru tua

        JLabel title = new JLabel("  Warehouse Inventory System");
        title.setForeground(Color.WHITE);
        title.setFont(new Font("Segoe UI", Font.BOLD, 18));

        JLabel user = new JLabel("Login sebagai: Admin  ");
        user.setForeground(Color.WHITE);

        header.add(title, BorderLayout.WEST);
        header.add(user, BorderLayout.EAST);

        PanelMain.add(header, BorderLayout.NORTH);
    }

    private void initPanelDesign() {
        panelMasterData.setLayout(new BorderLayout());
        panelTransaction.setLayout(new BorderLayout());
        panelReport.setLayout(new BorderLayout());

        panelMasterData.add(createTitle("MASTER DATA"), BorderLayout.NORTH);
        panelTransaction.add(createTitle("TRANSAKSI"), BorderLayout.NORTH);
        panelReport.add(createTitle("LAPORAN"), BorderLayout.NORTH);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        tabMain = new javax.swing.JTabbedPane();
        panelMasterData = new javax.swing.JPanel();
        panelTransaction = new javax.swing.JPanel();
        panelReport = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelMain.setLayout(new java.awt.BorderLayout());

        tabMain.setName("Master Data"); // NOI18N

        panelMasterData.setToolTipText(" ");
        panelMasterData.setName("panelMasterData"); // NOI18N

        javax.swing.GroupLayout panelMasterDataLayout = new javax.swing.GroupLayout(panelMasterData);
        panelMasterData.setLayout(panelMasterDataLayout);
        panelMasterDataLayout.setHorizontalGroup(
            panelMasterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        panelMasterDataLayout.setVerticalGroup(
            panelMasterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        tabMain.addTab("panelMasterData   ", null, panelMasterData, "");

        javax.swing.GroupLayout panelTransactionLayout = new javax.swing.GroupLayout(panelTransaction);
        panelTransaction.setLayout(panelTransactionLayout);
        panelTransactionLayout.setHorizontalGroup(
            panelTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        panelTransactionLayout.setVerticalGroup(
            panelTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        tabMain.addTab("panelTransaction", panelTransaction);

        javax.swing.GroupLayout panelReportLayout = new javax.swing.GroupLayout(panelReport);
        panelReport.setLayout(panelReportLayout);
        panelReportLayout.setHorizontalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        panelReportLayout.setVerticalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        tabMain.addTab("panelReport       ", panelReport);

        PanelMain.add(tabMain, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private JPanel createTitle(String text) {
        JPanel panel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        panel.setBackground(new Color(243, 244, 246)); // abu muda
        panel.setPreferredSize(new Dimension(0, 50));

        JLabel label = new JLabel(text);
        label.setFont(new Font("Segoe UI", Font.BOLD, 16));

        panel.add(label);
        return panel;
    }
    
public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel panelMasterData;
    private javax.swing.JPanel panelReport;
    private javax.swing.JPanel panelTransaction;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables
}
